name: test build
on:
  push:
    branches: [ dev ]
    paths:
      - 'pom.xml'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build application
        run: ./mvnw -Dmaven.test.skip=true clean package -P dev
      - name: Copy build
        run: |
          cp bdofishbot/target/blackdesert-fishbot.zip ~/docker-volume/uat/fishing-resources/blackdesert-fishbot.zip
      - name: Copy version
        run: |
          cp bdofishbot-base/target/classes/version ~/docker-volume/uat/fishing-resources/version.txt