name: prod build
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build application
        run: ./mvnw -Dmaven.test.skip=true clean package
      - name: Copy build
        run: |
          cp bdofishbot/target/blackdesert-fishbot.zip ~/docker-volume/prod/fishing-resources/blackdesert-fishbot.zip
      - name: Copy version
        run: |
          cp bdofishbot-base/target/classes/version ~/docker-volume/prod/fishing-resources/version.txt